### ISSUE TITLE
'My name is ...' badge not implemented

### ISSUE THREAD

**Issue by frankkienl** [Andon-A/DigiBadge#1]
https://github.com/Andon-A/DigiBadge/blob/master/colorbadge_nosd/colorbadge_nosd.ino#L26
// Badge 4 is "My name is..."

Badge 4 is not implemented in drawBadge.

**Comment by frankkienl** [comment]
I've created a patch that should enable My Name Is, on hacker-versions of the badge.
The users should enter the name in the source-code (thats why hacker-only) as the badge does not provide a keyboard. 
I have not tested the code as I don't have a badge ( yet ).

**Comment by Andon-A** [comment]
I had been fiddling with attempting to get a "Hello, My name is..." badge similar to the stickers you can find, such as: http://fc05.deviantart.net/fs17/i/2007/165/8/d/Hello_my_name_is_by_Kubah.png

I had encountered a few problems and decided to delay it, but apparently hadn't purged everything from the code.

My intention had been to request what name everyone would want on their badge so I could pre-program it in. That way even the non-hacker badges would be able to utilize it. I'll be revisiting it at some point.

**Comment by frankkienl** [comment]
Ah I see. Thanks for the explanation.
Keep up the good work ;-)
